### PR TITLE
Added Hipster

### PR DESCRIPTION
**Pull request by iLexiconn**

### CODE REVIEW

**Comment by lieuwex** [comment]
Is this an app? If so, we [don't accept it](https://github.com/DutchCodeGeeks/MagisterHub/pull/2#issuecomment-86462958).

**Comment by lieuwex** [comment]
Well wait, sorry, this is an open source app after all.

@DutchCodeGeeks/owners what do you think?

**Comment by iLexiconn** [comment]
Oh, I didn't read that conversation. You're talking about closed-source apps there, and this one is open-source. ;)

**Comment by tomsmeding** [comment]
Sounds reasonable to merge

**Comment by tkon99** [comment]
I think this is lib only. We could/should make an app section.

**Comment by lieuwex** [comment]
@tkon99 Yeah good idea, what would classify as an 'app'? Every project that isn't a lib? Is [Magister calendar](https://github.com/lesander/magister-calendar) an app? What about [Mahgister](https://github.com/lieuwex/MahGister)?

**Comment by tkon99** [comment]
Everything that is using a lib to handle the data. Everything that does communication with Magister on itself should create a separate repo for the communication and/or turn it into a lib as well.

**Comment by lieuwex** [comment]
@tkon99 
> Everything that does communication with Magister on itself should create a separate repo for the communication and/or turn it into a lib as well.

Uhm well, isn't that a bit too strict. Shouldn't we just put those repos in the app sector?

**Comment by tkon99** [comment]
Well, we could do that but then we have a huge grey area. What would the criteria for an app/lib be?

**Comment by lieuwex** [comment]
@tkon99 Well I guess we could say that everything that apps use to communicate with Magister counts as a 'lib' (so magister->json bridges would be 'libs' to). And everything that is like at the end of the user chain would be an 'app'.

**Comment by lieuwex** [comment]
Continued in #5

**Pull request closed without merging**
