### PR TITLE
Separate MagisterHub in app and lib sector

### PR DESCRIPTION
**Pull request by lieuwex**

### CODE REVIEW

**Comment by lieuwex** [comment]
I still don't know what to do with Magister-calendar tho

**Comment by tkon99** [comment]
That is the easiest one around... it uses MagisterJS so it isn't a lib.

**Comment by lieuwex** [comment]
@tkon99 Yeah of course, but I'm not sure under what header to place it, 'headless'?

**Comment by tkon99** [comment]
yeah. CLI, headless, something like that

**Comment by lieuwex** [comment]
Merge?

**Comment by lieuwex** [comment]
:+1:

**Pull request merged**
