### PR TITLE
Created and started making ApiDocumentation

### PR DESCRIPTION
**Pull request by KeizerDev**
hereby my begin of the Magister-Api documentation. I'll finish it tomorrow.

### CODE REVIEW

**Comment by lieuwex** [comment]
Looks great! Shall I wait untill you're finished before merging it, so you add extra commits to this PR or do you prefer it to be merged straight away?

**Comment by KeizerDev** [comment]
Uh, if I commit it automatically get added to my pull request, right? Because I've fixed some typo's and added todos so you can merge it now. So we already have at least something! I will finish it later! No that much time now, because I'm busy with a magister app too and I want it to launch asap.

**Comment by lieuwex** [comment]
@KeizerDev Yes, additional commits pushed to KeizerDev:master will appear here.
Okay! Good luck with your app. :D

**Comment by KeizerDev** [comment]
Could you please merge my last commit?

**Comment by lieuwex** [comment]
I can't merge it, but I will cherry-pick it.

**Comment by tkon99** [comment]
Closing this for now.

**Pull request closed without merging**
